---
output:
  pdf_document
---

### Bi-LSTM-CNN

| Class                     | Accuracy | Precision | Recall | F1 Score |
| ------------------------- | -------- | --------- | ------ | -------- |
| Benign                    | 97.99%   | 99.03%    | 98.47% | 98.75%   |
| Bot                       | 99.93%   | 0.00%     | 0.00%  | 0.00%    |
| DDos                      | 99.91%   | 99.81%    | 98.26% | 99.03%   |
| Dos GoldenEye             | 99.94%   | 96.47%    | 88.31% | 92.21%   |
| Dos Hulk                  | 99.26%   | 93.79%    | 97.39% | 95.56%   |
| DoS Slowhttptest          | 99.95%   | 86.06%    | 91.45% | 88.67%   |
| DoS Slowloris             | 99.96%   | 97.69%    | 80.40% | 88.20%   |
| FTP-Patator               | 99.97%   | 92.14%    | 97.84% | 94.90%   |
| Heartbleed                | 100.00%  | 0.00%     | 0.00%  | 0.00%    |
| Infiltration              | 100.00%  | 0.00%     | 0.00%  | 0.00%    |
| PortScan                  | 99.10%   | 89.36%    | 95.29% | 92.23%   |
| SSH-Patator               | 99.96%   | 86.66%    | 97.64% | 91.82%   |
| Web Attack: Brute Force   | 99.95%   | 100.00%   | 3.15%  | 6.12%    |
| Web Attack: Sql Injection | 100.00%  | 0.00%     | 0.00%  | 0.00%    |
| Web Attack: XSS           | 99.97%   | 0.00%     | 0.00%  | 0.00%    |


### KNN

| Class                          | Accuracy | Precision | Recall  | F1 Score |
| ------------------------------ | -------- | --------- | ------- | -------- |
| 0 (Benign)                     | 99.44%   | 99.78%    | 99.52%  | 99.65%   |
| 1 (Bot)                        | 99.95%   | 71.56%    | 59.01%  | 64.68%   |
| 2 (DDos)                       | 99.99%   | 99.92%    | 99.91%  | 99.91%   |
| 3 (Dos GoldenEye)              | 99.99%   | 97.20%    | 98.86%  | 98.02%   |
| 4 (Dos Hulk)                   | 99.95%   | 99.68%    | 99.72%  | 99.70%   |
| 5 (DoS Slowhttptest)           | 99.99%   | 98.24%    | 98.41%  | 98.33%   |
| 6 (DoS Slowloris)              | 99.99%   | 98.62%    | 98.88%  | 98.75%   |
| 7 (FTP-Patator)                | 100.00%  | 99.81%    | 99.32%  | 99.57%   |
| 8 (Heartbleed)                 | 100.00%  | 100.00%   | 80.00%  | 88.89%   |
| 9 (Infiltration)               | 100.00%  | 33.33%    | 16.67%  | 22.22%   |
| 10 (PortScan)                  | 99.58%   | 94.54%    | 98.04%  | 96.26%   |
| 11 (SSH-Patator)               | 99.99%   | 95.67%    | 98.82%  | 97.22%   |
| 12 (Web Attack: Brute Force)   | 99.97%   | 70.43%    | 76.66%  | 73.41%   |
| 13 (Web Attack: Sql Injection) | 100.00%  | 0.00%     | 0.00%   | 0.00%    |
| 14 (Web Attack: XSS)           | 99.97%   | 48.42%    | 30.46%  | 37.40%   |

\pagebreak

### Logistic Regression

| Class                          | Accuracy | Precision | Recall | F1 Score |
| ------------------------------ | -------- | --------- | ------ | -------- |
| 0 (Benign)                     | 95.99%   | 97.73%    | 97.28% | 97.50%   |
| 1 (Bot)                        | 99.93%   | 0.00%     | 0.00%  | 0.00%    |
| 2 (DDos)                       | 99.55%   | 98.96%    | 90.92% | 94.77%   |
| 3 (Dos GoldenEye)              | 99.79%   | 84.05%    | 52.09% | 64.32%   |
| 4 (Dos Hulk)                   | 98.85%   | 91.49%    | 94.69% | 93.07%   |
| 5 (DoS Slowhttptest)           | 99.88%   | 71.76%    | 62.52% | 66.82%   |
| 6 (DoS Slowloris)              | 99.88%   | 95.98%    | 45.34% | 61.58%   |
| 7 (FTP-Patator)                | 99.71%   | 48.84%    | 3.90%  | 7.22%    |
| 8 (Heartbleed)                 | 100.00%  | 0.00%     | 0.00%  | 0.00%    |
| 9 (Infiltration)               | 100.00%  | 0.00%     | 0.00%  | 0.00%    |
| 10 (PortScan)                  | 98.56%   | 79.84%    | 99.12% | 88.44%   |
| 11 (SSH-Patator)               | 99.79%   | 0.00%     | 0.00%  | 0.00%    |
| 12 (Web Attack: Brute Force)   | 99.94%   | 0.00%     | 0.00%  | 0.00%    |
| 13 (Web Attack: Sql Injection) | 100.00%  | 0.00%     | 0.00%  | 0.00%    |
| 14 (Web Attack: XSS)           | 99.97%   | 0.00%     | 0.00%  | 0.00%    |


### Random Forest

| Class                          | Accuracy | Precision | Recall  | F1 Score |
| ------------------------------ | -------- | --------- | ------- | -------- |
| 0 (Benign)                     | 99.80%   | 99.88%    | 99.87%  | 99.87%   |
| 1 (Bot)                        | 99.96%   | 80.86%    | 60.49%  | 69.21%   |
| 2 (DDos)                       | 99.99%   | 99.96%    | 99.93%  | 99.95%   |
| 3 (Dos GoldenEye)              | 99.98%   | 98.98%    | 96.82%  | 97.89%   |
| 4 (Dos Hulk)                   | 99.97%   | 99.80%    | 99.82%  | 99.81%   |
| 5 (DoS Slowhttptest)           | 99.99%   | 98.77%    | 98.77%  | 98.77%   |
| 6 (DoS Slowloris)              | 99.99%   | 99.47%    | 98.10%  | 98.78%   |
| 7 (FTP-Patator)                | 100.00%  | 99.88%    | 99.75%  | 99.81%   |
| 8 (Heartbleed)                 | 100.00%  | 100.00%   | 80.00%  | 88.89%   |
| 9 (Infiltration)               | 100.00%  | 50.00%    | 16.67%  | 25.00%   |
| 10 (PortScan)                  | 99.89%   | 98.79%    | 99.32%  | 99.05%   |
| 11 (SSH-Patator)               | 99.99%   | 99.66%    | 98.99%  | 99.32%   |
| 12 (Web Attack: Brute Force)   | 99.97%   | 72.29%    | 79.81%  | 75.86%   |
| 13 (Web Attack: Sql Injection) | 100.00%  | 50.00%    | 14.29%  | 22.22%   |
| 14 (Web Attack: XSS)           | 99.97%   | 47.17%    | 33.11%  | 38.91%   |


### Decision Tree

| Class                      | Accuracy  | Precision | Recall   | F1 Score | AUC      |
|----------------------------|-----------|-----------|----------|----------|----------|
| BENIGN                     | 99.75%    | 99.86%    | 99.83%   | 99.84%   | 99.63%   |
| Bot                        | 99.95%    | 63.16%    | 62.22%   | 62.69%   | 81.10%   |
| DDoS                       | 99.99%    | 99.86%    | 99.92%   | 99.89%   | 99.96%   |
| DoS GoldenEye              | 99.98%    | 96.60%    | 97.24%   | 96.92%   | 98.62%   |
| DoS Hulk                   | 99.96%    | 99.72%    | 99.80%   | 99.76%   | 99.90%   |
| DoS Slowhttptest           | 99.99%    | 97.64%    | 98.41%   | 98.02%   | 99.20%   |
| DoS slowloris              | 99.99%    | 98.78%    | 97.50%   | 98.13%   | 98.75%   |
| FTP-Patator                | 100.00%   | 99.51%    | 99.88%   | 99.69%   | 99.94%   |
| Heartbleed                 | 100.00%   | 100.00%   | 20.00%   | 33.33%   | 60.00%   |
| Infiltration               | 100.00%   | 14.29%    | 16.67%   | 15.38%   | 58.33%   |
| PortScan                   | 99.87%    | 98.84%    | 98.86%   | 98.85%   | 99.52%   |
| SSH-Patator                | 99.99%    | 98.41%    | 99.16%   | 98.78%   | 99.58%   |
| Web Attack – Brute Force   | 99.97%    | 71.77%    | 75.39%   | 73.54%   | 87.69%   |
| Web Attack – Sql Injection | 100.00%   | 20.00%    | 14.29%   | 16.67%   | 57.14%   |
| Web Attack – XSS           | 99.97%    | 42.65%    | 38.41%   | 40.42%   | 69.20%   |



### Gradient Boosted Decision Tree

| Class                         | Accuracy  | Precision | Recall   | F1 Score |
|-------------------------------|-----------|-----------|----------|----------|
| BENIGN                        | 98.44%    | 99.13%    | 98.93%   | 99.03%   |
| Bot                           | 99.95%    | 100.00%   | 27.65%   | 43.33%   |
| DDoS                          | 99.95%    | 99.43%    | 99.39%   | 99.41%   |
| DoS GoldenEye                 | 99.91%    | 94.23%    | 81.56%   | 87.44%   |
| DoS Hulk                      | 99.66%    | 97.51%    | 98.35%   | 97.93%   |
| DoS Slowhttptest              | 99.95%    | 91.24%    | 84.48%   | 87.73%   |
| DoS slowloris                 | 99.97%    | 99.10%    | 85.66%   | 91.89%   |
| FTP-Patator                   | 99.99%    | 99.68%    | 97.53%   | 98.59%   |
| Heartbleed                    | 100.00%   | 100.00%   | 80.00%   | 88.89%   |
| Infiltration                  | 100.00%   | 50.00%    | 16.67%   | 25.00%   |
| PortScan                      | 99.07%    | 89.45%    | 94.47%   | 91.89%   |
| SSH-Patator                   | 99.99%    | 97.11%    | 96.45%   | 96.78%   |
| Web Attack – Brute Force      | 99.95%    | 62.03%    | 15.46%   | 24.75%   |
| Web Attack – Sql Injection    | 100.00%   | 0.00%     | 0.00%    | 0.00%    |
| Web Attack – XSS              | 99.97%    | 0.00%     | 0.00%    | 0.00%    |


### FFNN

| Class                      | Accuracy  | Precision | Recall   | F1 Score |
|----------------------------|-----------|-----------|----------|----------|
| BENIGN                     | 98.20%    | 99.01%    | 98.75%   | 98.88%   |
| Bot                        | 99.95%    | 100.00%   | 33.09%   | 49.72%   |
| DDoS                       | 99.91%    | 99.85%    | 98.20%   | 99.02%   |
| DoS GoldenEye              | 99.95%    | 93.30%    | 94.68%   | 93.98%   |
| DoS Hulk                   | 99.41%    | 95.77%    | 97.07%   | 96.42%   |
| DoS Slowhttptest           | 99.95%    | 84.44%    | 90.92%   | 87.56%   |
| DoS slowloris              | 99.97%    | 94.65%    | 90.16%   | 92.35%   |
| FTP-Patator                | 99.98%    | 95.62%    | 98.58%   | 97.08%   |
| Heartbleed                 | 100.00%   | 0.00%     | 0.00%    | 0.00%    |
| Infiltration               | 100.00%   | 0.00%     | 0.00%    | 0.00%    |
| PortScan                   | 99.10%    | 89.99%    | 94.38%   | 92.13%   |
| SSH-Patator                | 99.98%    | 91.25%    | 97.80%   | 94.42%   |
| Web Attack – Brute Force   | 99.95%    | 76.92%    | 3.15%    | 6.06%    |
| Web Attack – Sql Injection | 100.00%   | 0.00%     | 0.00%    | 0.00%    |
| Web Attack – XSS           | 99.97%    | 0.00%     | 0.00%    | 0.00%    |


## GRU

| Class                          | Accuracy  | Precision | Recall   | F1 Score |
| ---------------------------    | --------- | --------- | -------- | -------- |
| BENIGN                         | 98.30%    | 99.19%    | 98.69%   | 98.94%   |
| Bot                            | 99.95%    | 100.00%   | 33.09%   | 49.72%   |
| DDoS                           | 99.98%    | 99.73%    | 99.80%   | 99.77%   |
| DoS GoldenEye                  | 99.94%    | 91.66%    | 92.44%   | 92.05%   |
| DoS Hulk                       | 99.59%    | 96.12%    | 98.96%   | 97.52%   |
| DoS Slowhttptest               | 99.93%    | 79.41%    | 90.83%   | 84.74%   |
| DoS slowloris                  | 99.95%    | 88.60%    | 85.23%   | 86.88%   |
| FTP-Patator                    | 99.89%    | 72.24%    | 98.33%   | 83.30%   |
| Heartbleed                     | 100.00%   | 0.00%     | 0.00%    | 0.00%    |
| Infiltration                   | 100.00%   | 100.00%   | 16.67%   | 28.57%   |
| PortScan                       | 99.08%    | 90.64%    | 93.15%   | 91.88%   |
| SSH-Patator                    | 99.97%    | 90.45%    | 97.64%   | 93.91%   |
| Web Attack – Brute Force       | 99.95%    | 100.00%   | 3.15%    | 6.12%    |
| Web Attack – Sql Injection     | 100.00%   | 0.00%     | 0.00%    | 0.00%    |
| Web Attack – XSS               | 99.97%    | 0.00%     | 0.00%    | 0.00%    |
